//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgrammersAdda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public string userid { get; set; }
        public string passwd { get; set; }
    }
}
